### ISSUE TITLE
Curly braces deprecated in php 7.4 in Thrift package

### ISSUE THREAD

**Issue by Bartoszk31** [jonahgeorge/jaeger-client-php#100]
Hi,

I have got an error on php 7.4
Array and string offset access syntax with curly braces is deprecated in /var/www/vendor/packaged/thrift/src/Thrift/Transport/THttpClient.php
on line 100

There is a fix in thrift package in version 0.14.1
https://github.com/apache/thrift/commit/44b0b5d3c9b2bcaae43470bfe98721d0281958e5

Is there any chance that can you upgrade version of Thrift to 0.14.1?

**Comment by sergeyklay** [comment]
Fixed in https://github.com/jonahgeorge/jaeger-client-php/pull/101. I've [released v1.2.1](https://github.com/jonahgeorge/jaeger-client-php/releases/tag/v1.2.1) just now. Feel free to open a new issue if the problem appears again. Thank you for contributing.
