### ISSUE TITLE
Booleans in tags are casted to string

### ISSUE THREAD

**Issue by Bartoszk31** [jonahgeorge/jaeger-client-php#102]
Hi,

When i add a tag named error and set its value to true it is casted to 1.
If Jaeger UI get a span with tag error with true boolean value it has an exclamation mark next to it.
It helps to fast locate an error in application.
The problem occures after last commit - Jaeger Thrift over Binary protocol implementation (UDP 6832 & Http 14… 
I tried to send spans over UDP port 6832 and TCP port 14268, in both cases it cast boolean to string.

I made some code changes localy in files:
\Jaeger\Span
`
...
const SPECIAL_TAGS = [
        PEER_SERVICE => 'setPeerService',
        PEER_HOST_IPV4 => 'setPeerHostIpv4',
        PEER_PORT => 'setPeerPort',
        SPAN_KIND => 'setSpanKind',
        COMPONENT => 'setComponent',
        'error' => 'setError',
    ];

    private function setError($value): bool
    {
        $this->tags['error'] = new BinaryAnnotation([
            'key' => 'error',
            'value' => $value,
            'annotation_type' => AnnotationType::BOOL,
        ]);

        return true;
    }
...
`
\Jaeger\Mapper\SpanToJaegerMapper
`
...
public function mapSpanToJaeger(Span $span) : JaegerThriftSpan
    {
        $timestamp = $span->getStartTime();
        $duration = $span->getEndTime() - $span->getStartTime();

        /** @var Tag[] $tags */
        $tags = [];

        $tags[] = new Tag([
            "key" => COMPONENT,
            "vType" => TagType::STRING,
            "vStr" => $span->getComponent() ?? $span->getTracer()->getServiceName(),
        ]);

        /** @var BinaryAnnotation[] $binaryAnnotationTags */
        $binaryAnnotationTags = $span->getTags();
        foreach ($binaryAnnotationTags as $binaryAnnotationTag) {
            if (in_array($binaryAnnotationTag->key, $this->specialSpanTags, true)) {
                continue ;
            }

            if (strpos($binaryAnnotationTag->key, $this->processTagsPrefix) === 0) {
                continue;
            }

            if ($binaryAnnotationTag->key === 'error') {
                $tags[] = new Tag([
                    "key" => $binaryAnnotationTag->key,
                    "vType" => TagType::BOOL,
                    "vBool" => $binaryAnnotationTag->value,
                ]);

                continue;
            }

            $tags[] = new Tag([
                "key" => $binaryAnnotationTag->key,
                "vType" => TagType::STRING,
                "vStr" => $binaryAnnotationTag->value,

            ]);
        }

        /** @var Log[] $logs */
        $logs = [];

        $spanLogs = $span->getLogs();

        foreach ($spanLogs as $spanLog) {
            /** @var Tag $fields */
            $fields = [];

            if (!empty($spanLog["fields"])) {
                $fields[] = new Tag([
                    "key" => "event",
                    "vType" => TagType::STRING,
                    "vStr" => json_encode($spanLog["fields"])
                ]);
            }

            $logs[] = new Log([
                "timestamp" => $spanLog["timestamp"],
                "fields" => $fields
            ]);
        }

        return new JaegerThriftSpan([
            "traceIdLow" => (int)$span->getContext()->getTraceId(),
            "traceIdHigh" => 0,
            "spanId" => (int)$span->getContext()->getSpanId(),
            "parentSpanId" => (int)$span->getContext()->getParentId(),
            "operationName" => $span->getOperationName(),
            "startTime" => $timestamp,
            "duration" => $duration,
            "flags" => (int)$span->isDebug(),
            "tags" => $tags,
            "logs" => $logs
        ]);
    }
...
`
After this changes error tag is sending boolean and it is marked in UI as error with exclamation mark.
Is there any chance to implement casting error tag to bool?

**Comment by sergeyklay** [comment]
Hello @Bartoszk31,

Fixed in version v1.2.2.  Feel free to open a new issue if the problem appears again. Thank you for the report, and for helping us make Jaeger Client better!
