### ISSUE TITLE
Support PHP 5.6

### ISSUE THREAD

**Issue by jonahgeorge** [jonahgeorge/jaeger-client-php#11]

**Comment by jonahgeorge** [comment]
PHP 5.6 is no longer actively supported and will stop being supported for security updates by end of year.

http://php.net/supported-versions.php

**Comment by jonahgeorge** [comment]
Reopening this as it's part of the considering for migration into jaegertracing org

**Comment by blong14** [comment]
@jonahgeorge I can take a look at this one. The plan would be to wire up some documentation on how to test different PHP versions via docker (docker run --rm...) for local testing. Add the necessary PHP version constraint to travis. Finally, update the code where necessary. Thoughts?

**Comment by blong14** [comment]
@jcchavezs what state is your branch in that adds support for 5.6?

**Comment by jonahgeorge** [comment]
With the release of 0.3.0, almost all code has at least a partial test and type hints in the docblock- so adding support for 5.6 should be as simple as removing the primitive type hints in the function signatures. 

I'm not convinced that adding a docker setup is necessary as long as Travis has 5.6 in the test matrix. I would imagine most people will just install another version of PHP and switch their symlinks.

**Comment by blong14** [comment]
I was just thinking adding to the README how one could run a container to test a specific version of php, so there wouldn't be any code to include Dockerfiles or anything like, but having it in travis is fine.

**Comment by jonahgeorge** [comment]
Ah, gotcha. Yea that sounds perfects

**Comment by benkeil** [comment]
+1

**Comment by blong14** [comment]
@jonahgeorge I'm working out things for this. Not yet ready for a pull request but I think some feedback would be nice. Versions 5.6 and 7.0 aren't running as there seems to be some composer dependencies that rely on 7.1? 

 [Diff with master](https://github.com/jonahgeorge/jaeger-client-php/compare/master...blong14:php-version-testing)

**Comment by blong14** [comment]
Also, once composer is updated appropriately for all versions pull request will be issued. Once merged I'll start working on the application code updates to handle changes necessary for 5.6.
