### ISSUE TITLE
How to ensure closing?

### ISSUE THREAD

**Issue by maiermic** [jonahgeorge/jaeger-client-php#110]
If you have multiple operations that should be wrapped by spans. How do you ensure that the span/scope is closed, even if an exception is thrown by one of the operations?

**Example:**

```php
$tracer = GlobalTracer::get();
register_shutdown_function(function () {
  GlobalTracer::get()->flush();
});

try {
  $scope = $tracer->startActiveSpan('doA', []);
  doA();
  $scope->close();
  $scope = $tracer->startActiveSpan('doB', []);
  doB();
} finally {
  // may be unset if `$tracer->startActiveSpan` throws an exception
  if (isset($scope)) {
    $scope->close();
  }
}
```

IMO this is quite verbose. Besides, what if `$scope->close();` throws an exception?

What (e.g. pattern) do you recommend?

**Comment by maiermic** [comment]
I'd like to set the tag `error=true` if an exception is thrown. It is quite redundant to set this tag in each catch. Is there a better way?

```php
try {
  $scope = $tracer->startActiveSpan('doA', []);
  doSomething();
} catch (FooException $e) {
  handleFooException($e);
  $scope->getSpan()->setTag('error', true);
} catch (BarException $e) {
  handleBarException($e);
  $scope->getSpan()->setTag('error', true);
} catch (FoobarException $e) {
  handleFoobarException($e);
  $scope->getSpan()->setTag('error', true);
} finally {
  // may be unset if `$tracer->startActiveSpan` throws an exception
  if (isset($scope)) {
    $scope->close();
  }
}
```

**Comment by sergeyklay** [comment]
> What (e.g. pattern) do you recommend?

How about registering a callback to finish tracing? Something like that should work:

```php
register_shutdown_function(function () {
    GlobalTracer::get()->finish();
});
```

**Comment by sergeyklay** [comment]
> @sergeyklay There is no such method as `GlobalTracer::get()->finish();`.

Oh yes, I messed up with our implementation. We use our own wrapper to make things easier. Well, the most reliable way is to implement all the functionality you need in your own wrapper.  I will show only part of the code, but I hope that you understand what the main idea is.


```php
    public function finish()
    {
        /** @var SpanInterface[] $spans */
        $spans = array_reverse($this->spans);

        foreach ($spans as $span) {
            $this->finishSpan($span);
        }

        $rootSpan = $this->rootSpan;
        if ($this->rootSpan) {
            if ($this->newOperationName) {
                $this->rootSpan->overwriteOperationName($this->newOperationName);
            }

            $this->rootSpan->finish();
            $this->rootSpan = null;
        }

        $this->newOperationName = null;
        if ($rootSpan) {
            $this->tracer->flush();
        }
        GlobalTracerBridge::unset();
    }
```

**Comment by maiermic** [comment]
@sergeyklay Thank you for sharing. Do you only call `finish` in `register_shutdown_function `? Can this handle the example, I added to my [comment](https://github.com/jonahgeorge/jaeger-client-php/issues/110#issuecomment-925048029) in the last edit, i.e. span 'doB' should **not** be added as child to span 'doA' if `doA` threw an exception.

**Comment by sergeyklay** [comment]
Yes, it works exactly this way.

**Comment by maiermic** [comment]
@sergeyklay Well, I don't see how it works in my example? 😕  As far as I can tell, `finish` is called after

```php
$tracer->startActiveSpan('doB', []);
```

has been called, isn't it? In that case, span 'doB' is added as child to span 'doA' (if `doA` threw an exception) before `finish` is called. Does `finish` undo this? How?

**Comment by sergeyklay** [comment]
If doA threw an exception, the shutdown will be called, isn't? In this case finish will close active span.

**Comment by maiermic** [comment]
**Yes**, in the example of the [ticket description](https://github.com/jonahgeorge/jaeger-client-php/issues/110#issue-1004401314).

**No**, not in the example of the [comment](https://github.com/jonahgeorge/jaeger-client-php/issues/110#issuecomment-925048029) I referred to, since `doA` is called in `doSomething`, which is called like this

```php
try {
  doSomething();
} catch (Exception $e) {
  // handle exception and continue running
}
```

The exception of `doA` is forwarded from `doSomething` and caught outside (see `catch` above). Then the app continues to run and creates another span for `doB`.

**Comment by sergeyklay** [comment]
AFAIK, there is no standard way (or practice) to close spans in case when you catch exceptions and don't re-throw them. What do you can do is to throw exception, catch it in error handler, fire error event and habdle this event in the listener. A listener should get global tracer, loop over spans stack and drop all right before first error.
