### ISSUE TITLE
How to create multiple tracers?

### ISSUE THREAD

**Issue by maiermic** [jonahgeorge/jaeger-client-php#111]
The example in the Readme only shows how to create/initialize the `GlobalTracer`. How to create another (local) tracer (e.g. for SQL spans)?

At least, I'd like to get spans in jaeger shown in a different color if they do not belong to my backend, but to the database. See screenshot from [Jaeger documentation](https://www.jaegertracing.io/docs/1.26/):

![](https://www.jaegertracing.io/img/trace-detail-ss.png)

Are multiple tracers the wrong approach for this?

**Comment by sergeyklay** [comment]
Never used more than one tracer. In the provided screenshot, different spans are marked with the same color (and not just the database). Could you give an example/screenshot of what you are trying to change?

**Comment by sergeyklay** [comment]
AFAIK, there is no standard way (or practice) to close spans in case when you catch exceptions and don't re-throw them. What do you can do is to throw exception, catch it in error handler, fire error event and habdle this event in the listener. A listener should get global tracer, loop over spans stack and drop all right before first error.

**Comment by sergeyklay** [comment]
Got it. Well, I'm not sure this is configurable by jaeger-client-php. I even not sure this being supported by the protocol. As far as I know for color detection is responsible [Jaeger UI](https://github.com/jaegertracing/jaeger-ui) project.

**Comment by pekhota** [comment]
Your problem is more related to the jaeger ui rather than jaeger client. There is an old issue there https://github.com/jaegertracing/jaeger-ui/issues/38. You can get some details from it. Also jaeger has some config options https://www.jaegertracing.io/docs/1.26/frontend-ui/ for their ui. Maybe it would be helpful for you.  

Overall I don't recommend you to use multiple tracers because 1 instance of tracer means 1 application you are going to trace. Having more than 1 tracer means that you will break this abstraction. Maybe you need add some tag to database spans and use ui search for that. 

But, if you insist here is the solution:

```php
$tracers = [];

for ($i = 0; $i < 5; $i++) {
    $config = new Config(
        [
            'local_agent' => [
                'reporting_host' => json_encode([
                    "host" => 'jaeger',
                    "ipProtocol" => "ipv6"
                ]),
            ],
            'sampler' => [
                'type' => Jaeger\SAMPLER_TYPE_CONST,
                'param' => true,
            ],
            'logging' => true,
            'dispatch_mode' => Config::JAEGER_OVER_BINARY_UDP,
        ],
        sprintf('your-app-name%d', $i),
        new StdErrLogger()
    );

    $reporter = (new JaegerReporterFactory($config))->createReporter();
    $sampler = new ConstSampler(true);

    $tracer = $config->createTracer($reporter, $sampler);
    $tracers[] = $tracer;
}


foreach ($tracers as $tracer) {
    $scope1 = $tracer->startActiveSpan('TestSpan1', []);

    for ($j = 0; $j < 4; $j++) {
        $scope2 = $tracer->startActiveSpan(sprintf("Child %d; level 1", $j));
        for ($i = 0; $i < 520; $i++) {
            $scope3 = $tracer->startActiveSpan(sprintf("Child %d level 2", $i));
            $scope3->close();
        }
        $scope2->close();
    }

    $scope1->close();

    $tracer->flush();
}
```

**Comment by maiermic** [comment]
> There is an old issue there jaegertracing/jaeger-ui#38.

That's a different issue about using different colors for the same service name:

> The trace view currently colors spans by the service name only, so calls between different instances of the same service are colored the same

I'd like to trace the SQL service (different service name than `backend`). AFAIK this can not be done in the SQL service (server) itself and has to be done by the SQL client (i.e. my PHP backend). Therefore, I somehow have to change the service name.

As far as I understand, this is what the [Hot R.O.D. example](https://github.com/jaegertracing/jaeger/tree/master/examples/hotrod) (written in Go) does. It changes the service name (as you can see in this [article](https://medium.com/opentracing/take-opentracing-for-a-hotrod-ride-f6e3141f7941))

![Trace timeline view](https://miro.medium.com/max/2000/1*ph6PiyKcEXv42UP1BXhZMA.png)

I'm not sure, how this is done in the Go client and how it is supposed to be done in the PHP client. The `Jaeger\Config` takes a service name as argument, but maybe this is not the correct way to change the service of a SQL span.

Is it a peer service? It seems to me that the tag [peer.service](https://github.com/opentracing/opentracing-go/blob/657cde1b36d1913fde8626bc73fc97c64728d94c/ext/tags.go#L66) is set in [services/customer/database.go](https://github.com/jaegertracing/jaeger/blob/a40ca4fd116b99563052e6c6b5315b14a9789e83/examples/hotrod/services/customer/database.go#L79). If I set this tag in the PHP client

```php
$span->setTag("peer.service", "mysql");
```

the tag is strangely not displayed in the Jaeger UI. Why? Is this tag maybe not supported by the PHP client? Or am I missing something else?

Do you even trace SQL service?

**Comment by maiermic** [comment]
The Hot R.O.D. example [runs multiple services](https://github.com/jaegertracing/jaeger/blob/343fcc6ddd3bdb94dec864bddc2ff8794d6666a8/examples/hotrod/cmd/all.go), but the customer service has two tracer. The first is [created](https://github.com/jaegertracing/jaeger/blob/0bdcec83422934a4cf907953ccf8a6646d1db171/examples/hotrod/cmd/customer.go#L40) with service name `customer` 

```go
server := customer.NewServer(
	net.JoinHostPort("0.0.0.0", strconv.Itoa(customerPort)),
	tracing.Init("customer", metricsFactory, logger),
	metricsFactory,
	logger,
)
```

In `customer.NewServer` the second tracer with service name `mysql` is [created](https://github.com/jaegertracing/jaeger/blob/0bdcec83422934a4cf907953ccf8a6646d1db171/examples/hotrod/services/customer/server.go#L46)

```go
func NewServer(hostPort string, tracer opentracing.Tracer, metricsFactory metrics.Factory, logger log.Factory) *Server {
	return &Server{
		hostPort: hostPort,
		tracer:   tracer,
		logger:   logger,
		database: newDatabase(
			tracing.Init("mysql", metricsFactory, logger),
			logger.With(zap.String("component", "mysql")),
		),
	}
}
```

So I guess, the correct way are multiple tracers to trace SQL service from your client.

**Comment by maiermic** [comment]
Thanks, for your help. It is working 😎 

![image](https://user-images.githubusercontent.com/8530117/135711925-573a9288-05db-42dc-b3b0-9571e1c362bf.png)


```php
<?php
require_once __DIR__.'/lib/vendor/autoload.php';

use Jaeger\Config;
use Jaeger\ReporterFactory\JaegerReporterFactory;
use Jaeger\Sampler\ConstSampler;
use OpenTracing\GlobalTracer;

$sharedJaegerConfiguration = [
  'sampler' => [
    'type' => Jaeger\SAMPLER_TYPE_CONST,
    'param' => true,
  ],
  'logging' => true,
  "tags" => [],
  "local_agent" => [
    "reporting_host" => "jaeger",
  ],
  'dispatch_mode' => Config::JAEGER_OVER_BINARY_UDP,
];
$globalConfig = new \Jaeger\Config(
  $sharedJaegerConfiguration,
  'backend'
);
$globalConfig->initializeTracer();
$config = new \Jaeger\Config(
  $sharedJaegerConfiguration,
  'mysql'
);
$globalTracer = GlobalTracer::get();

$scope = $globalTracer->startActiveSpan('BackendSpan', []);
$backendSpan = $scope->getSpan();

$reporter = (new JaegerReporterFactory($config))->createReporter();
$sampler = new ConstSampler(true);
$sqlTracer = $config->createTracer($reporter, $sampler);
$nestedSpanScope = $sqlTracer->startActiveSpan("MySQLSpan", [
  'child_of' => $backendSpan,
]);
sleep(1);
$nestedSpanScope->close();
$sqlTracer->flush();

sleep(1);
$scope->close();
$globalTracer->flush();
```
