### ISSUE TITLE
Add psr/cache 2.0 support

### ISSUE THREAD

**Issue by Taarim** [jonahgeorge/jaeger-client-php#116]
Using this package with symfony we cant update framework to 6.* version.

required cache/array-adapter library already supports cache 2.0 version

```
cache/adapter-common      1.3.0  requires  psr/cache (^1.0 || ^2.0)  
cache/array-adapter       1.2.0  requires  psr/cache (^1.0 || ^2.0)  
cache/hierarchical-cache  1.2.0  requires  psr/cache (^1.0 || ^2.0)  
cache/tag-interop         1.1.0  requires  psr/cache (^1.0 || ^2.0)
```

**Comment by sergeyklay** [comment]
Released https://github.com/jonahgeorge/jaeger-client-php/releases/tag/v1.4.0

Thank you for the implementation!
