### ISSUE TITLE
PHP 8.1 throws warning with package

### ISSUE THREAD

**Issue by waleedfaridworkland** [jonahgeorge/jaeger-client-php#118]
Running  this package on PHP 8.1, returns a php notice

Deprecated: Return type of Jaeger\SpanContext::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/vendor/jonahgeorge/jaeger-client-php/src/Jaeger/SpanContext.php on line 48

**Comment by sergeyklay** [comment]
@waleedfaridworkland Could you please send a patch?

**Comment by waleedfaridworkland** [comment]
@sergeyklay The thing is, despite changing 

Jaeger\SpanContext::getIterator() 
to 
Jaeger\SpanContext::getIterator(): Traversable

Or even adding the #[\ReturnTypeWillChange] attribute, makes no difference.

I am not entirely sure why.

**Comment by sergeyklay** [comment]
Just released [v1.4.1](https://github.com/jonahgeorge/jaeger-client-php/releases/tag/v1.4.1) with a fix. Thank you @dkemper for quick fix!

/cc @conserj
