### ISSUE TITLE
TextCodec produces malformed trace identity, trace/span ids should be exactly 16 characters

### ISSUE THREAD

**Issue by shadz3rg** [jonahgeorge/jaeger-client-php#129]
Hello,
Jaeger [guideline states](https://www.jaegertracing.io/docs/1.22/client-libraries/#value) `Senders SHOULD generate hex strings of exactly 16 or 32 characters in length`,
but algo chosen for [span id generator](https://github.com/jonahgeorge/jaeger-client-php/blob/3173d9c68ad8cea16058f25337982b00cc3d1c2b/src/Jaeger/Tracer.php#L361) and [hex converter](https://github.com/jonahgeorge/jaeger-client-php/blob/3173d9c68ad8cea16058f25337982b00cc3d1c2b/src/Jaeger/Codec/TextCodec.php#L143) produces value not consistent in length (depends on randomized id, making it so hard to debug as 9/10 span ids is correct), in that case it should be padded with leading zeros.
Most recievers will be fine with it and will auto-correct value, but integrating software with abstract request-ids can be tricky and hard to maintain consistency.

Quick gist, run N times:
```php
<?php
$rng = random_int(0, PHP_INT_MAX);
var_dump($rng);
 
$hex = sprintf('%x', (string) $rng);
var_dump('got', $hex);

$hex = sprintf('%016x', (string) $rng);
var_dump('expected', $hex);
```

Will result:
![image](https://github.com/jonahgeorge/jaeger-client-php/assets/2261823/177fa544-3dd1-437c-9b24-4a9f98a2d829)

**Comment by sergeyklay** [comment]
Fixed in v1.5.0. Feel free to open a new issue if the problem appears again. Thank you for contributing.
