### ISSUE TITLE
Pass by reference?

### ISSUE THREAD

**Issue by blong14** [jonahgeorge/jaeger-client-php#21]
Should $carrier be passed by reference here? 

https://github.com/jonahgeorge/jaeger-client-php/blob/42d4316f39d3ed329d2f1239e4fba8b30cc15a67/src/Jaeger/Codec/TextCodec.php#L33

Please excuse my lack of PHP knowledge as I am still learning the language. I'm calling Inject on the tracer to fill in a carrier with the span context information.

```
$carrier = [];

$this->getGlobalTracer()->inject(
      $span->getContext(),
      TEXT_MAP,
      $carrier
 );

return $carrier;
```

**Comment by jonahgeorge** [comment]
Hey! You're totally right about that. Is this something you're interesting in fixing? Otherwise I'll probably get to it when updating to the new opentracing version

**Comment by blong14** [comment]
Hello,

Yeah, I can take a crack at it. I'll see how far I can get and will issue a pull request soon.
