### ISSUE TITLE
Upgrade OpenTracing to beta5

### ISSUE THREAD

**Issue by jonahgeorge** [jonahgeorge/jaeger-client-php#28]
Now that the span propagation code has a settled a bit, it's time to update this library 🙌 

https://github.com/opentracing/opentracing-php/releases/tag/1.0.0-beta5

**Comment by blong14** [comment]
@jonahgeorge any updates on this? Anything specific you need help with? I'm open to contributing more but could use just a bit of direction. If there is nothing to do, no worries at all.

**Comment by jonahgeorge** [comment]
Work is nearing completion on branch `opentracing-beta5`. If you want to try this in your own application and report any bugs, I would greatly appreciate it.

**Comment by blong14** [comment]
@jonahgeorge I can make a request and see spans in the Jaeger UI. I'm currently using startActiveSpan and working with the scope API which seems to be working. I would say that my application is very simple and I am not tagging or logging anything on the spans or doing anything complicated, so do keep that in mind.

**Comment by jonahgeorge** [comment]
That's great news! Do you happen to be using `TextCodec`? I had to change the hex to decimal function to be compatible with PHP 7.0 and ended up changing the behavior slightly. 

- https://github.com/jonahgeorge/jaeger-client-php/blob/opentracing-beta5/tests/Jaeger/Codec/TextCodecTest.php#L31-L41
- https://github.com/jonahgeorge/jaeger-client-php/blob/opentracing-beta5/src/Jaeger/Codec/TextCodec.php#L67-L140

**Comment by jonahgeorge** [comment]
Barring no complications, I'll try to cut an initial release with beta5 by Wednesday

**Comment by blong14** [comment]
I guess technically I am via $tracer->extract but I don't currently have a client setup thats passing span context to the server.
