### ISSUE TITLE
Add Sender\HttpSender

### ISSUE THREAD

**Issue by jonahgeorge** [jonahgeorge/jaeger-client-php#37]
For sending jaeger.thrift over binary protocol to a collector running on port 14268 via HTTP

Resources:
- https://github.com/jaegertracing/jaeger-client-java/blob/dfb9d8b9dc849f2e6f880b44b26fb77dfc894a02/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/HttpSender.java

**Comment by jonahgeorge** [comment]
Blocked by #38

**Comment by sergeyklay** [comment]
Implemented in https://github.com/jonahgeorge/jaeger-client-php/pull/99
