### ISSUE TITLE
Switch to Jaeger.Thrift protocol

### ISSUE THREAD

**Issue by jonahgeorge** [jonahgeorge/jaeger-client-php#38]
Resources:
- https://github.com/jaegertracing/jaeger-client-node/blob/a78629002c39338d56e579095c9f3a35ed603f81/src/reporters/remote_reporter.js
- https://github.com/jaegertracing/jaeger-client-node/blob/a78629002c39338d56e579095c9f3a35ed603f81/src/reporters/udp_sender.js
- https://github.com/jaegertracing/jaeger-client-java/blob/dfb9d8b9dc849f2e6f880b44b26fb77dfc894a02/jaeger-thrift/src/main/java/io/jaegertracing/thrift/internal/senders/ThriftSender.java

**Comment by piotrooo** [comment]
Hello,
you have any plans/idea how to implement this feature?

**Comment by piotrooo** [comment]
Hello,
is it done?

**Comment by sergeyklay** [comment]
Implemented in https://github.com/jonahgeorge/jaeger-client-php/pull/99
