### ISSUE TITLE
The sockets extension is mandatory

### ISSUE THREAD

**Issue by izabolotnev** [jonahgeorge/jaeger-client-php#40]
I faced an exception Call to undefined function Jaeger\socket_create()
Looks like require.ext-sockets is forgotten in composer.json

**Comment by jonahgeorge** [comment]
Ah, sorry about that! I'll have that fixed up shortly

**Comment by myloveGy** [comment]
Here's the problem. If I don't need sockets and just use http, I don't have to rely on sockets
Packages cannot be downloaded because they rely on ext-sockets
