### ISSUE TITLE
Support 128-bit  Trace IDs

### ISSUE THREAD

**Issue by jonahgeorge** [jonahgeorge/jaeger-client-php#42]
The B3 spec can be up to 128-bits: `463ac35c9f6413ad48485a3953bb6124`

- https://github.com/openzipkin/b3-propagation
- https://github.com/jaegertracing/jaeger/issues/858

**Comment by bnubobby** [comment]
Hello,
is it done?

**Comment by sergeyklay** [comment]
Implemented in v1.5.0. Feel free to open a new issue if the problem appears again. Thank you for contributing.
