### ISSUE TITLE
PHP Coding Standards Fixer

### ISSUE THREAD

**Issue by piotrooo** [jonahgeorge/jaeger-client-php#47]
Hello,
are you interested of using a [PHP Coding Standards Fixer](https://cs.sensiolabs.org/) in a whole code, `src` and `tests`?

This made code well formatted, with the same indents, blank lines etc.
If you are interested I could make a PR.

**Comment by jonahgeorge** [comment]
Definitely! @blong14 added some linting in his #46 PR that you might be able to reuse.
Ideally, I would want the linter to fail the Travis build if it detects any issues.
Thanks 😃

**Comment by blong14** [comment]
I plan to work through @jonahgeorge comments today or tomorrow so as to get this in master. We can then update whatever is needed with better linting/coding standards.

**Comment by piotrooo** [comment]
@blong14 you wanna use a some special linting standards or just defaults, provided by the PHP-CSFixer?

**Comment by piotrooo** [comment]
@jonahgeorge another thing, but a little bit connected. Maybe this is a good time for remove all 'dead' code from project, there are a lot mess in code, there is any reason for this?

**Comment by sergeyklay** [comment]
How about [phpstan](https://github.com/phpstan/phpstan) then?

**Comment by jonahgeorge** [comment]
@piotrooo Hah, no reason for the dead code, just a product of slowly developing this. I'm entirely amenable to changing any part of this project, just don't have the bandwidth to do it all myself right now.

I think the one of the next big things is implementing the crossdock test suite so that any code refactoring doesn't lead to a regression.

**Comment by jonahgeorge** [comment]
[Phan](https://github.com/phan/phan) is another potential option here.

**Comment by piotrooo** [comment]
Docker was my next proposal to implement into the project. I don't have a
PHP localy on my PC. So running a tests are a little bit confusing for me.

pon., 16.07.2018, 22:54 użytkownik Jonah George <notifications@github.com>
napisał:

**Comment by piotrooo** [comment]
Are we need to support PHP 5.6? This version is almost dead, this version has only security support until end of the year.

**Comment by sergeyklay** [comment]
Closing, this is implemented. There is no code style errors: https://travis-ci.org/jonahgeorge/jaeger-client-php. If there are bugs/issue, we can follow up in separate issues. I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks.
