### ISSUE TITLE
DGRAM buffer limit and ignoring socket_send warnings

### ISSUE THREAD

**Issue by covobo** [jonahgeorge/jaeger-client-php#62]
Hi,
I'm working on integration your client with my symfony project.
I found a questionable decision, look at ThriftUdpTransport.php:99 (https://github.com/jonahgeorge/jaeger-client-php/blob/master/src/Jaeger/ThriftUdpTransport.php).
Why have you decided to ignore warnings?
The client has a buffer limit which is equal 64000 bytes, but MacOS has 9216 bytes limit by default (at least on MacOS Hight Sierra), the command to check sysctl net.inet.udp.maxdgram.
When I flushed a trace with thousands of spans I was getting nothing, no errors, no a trace on Jaeger, nothing.
It took much  time before I found that MacOS has 9216 bytes limit for udp dgram...

**Comment by sergeyklay** [comment]
Now these warning lead to TTransportException. Btw, buffer size is configurable:

https://github.com/jonahgeorge/jaeger-client-php/blob/98b3af3fa22ec6397abf8cfdad2777be21a69410/src/Jaeger/Config.php#L240-L243
