### ISSUE TITLE
Allow probabilistic sampler with rate 0 and 1

### ISSUE THREAD

**Issue by masterada** [jonahgeorge/jaeger-client-php#63]
```
        if ($rate <= 0.0 || $rate >= 1.0) {
            throw new OutOfBoundsException('Sampling rate must be between 0.0 and 1.0.');
        }
```
should be
```
        if ($rate < 0.0 || $rate > 1.0) {
            throw new OutOfBoundsException('Sampling rate must be between 0.0 and 1.0.');
        }
```

It would be easier to configure development sampler (can use the same sampler type with 1.0 rate), it would be easier to implement adaptive sampler and it's consitent with go client (didn't check other clients): https://github.com/jaegertracing/jaeger-client-go/blob/master/sampler.go#L111

**Comment by jonahgeorge** [comment]
Hah, that was a dumb oversight. If you'd like to make PRs for those changes, I'd happily merge them
