### ISSUE TITLE
Don't work 

### ISSUE THREAD

**Issue by Shketkol** [jonahgeorge/jaeger-client-php#77]
Composer.json 
"jonahgeorge/jaeger-client-php": "*"

Within controller
`$config = new Config(
        [
            'sampler' => [
                'type' => 'const',
                'param' => true,
            ],
            'logging' => true,
            ],
            'test'
        );
        $config->initializeTracer();

        $tracer = GlobalTracer::get();

        $scope = $tracer->startSpan('TestSpan');
        $scope->finish();

        $tracer->flush();`
But when I go to http://localhost:16686/search 
I don't see service 'test'

**Comment by sergeyklay** [comment]
Why you don't use `startActiveSpan`? Did you setup Jaeger dashboard properly? Do see you records in the storage? Have you profiled UDP traffic? Which Client/PHP/Jaeger version do you use? Please fill out the issue properly and completely, and do not make us guess.

**Comment by Shketkol** [comment]
Composer.json
"jonahgeorge/jaeger-client-php": "^0.4.3",
"opentracing/opentracing": "1.0.0-beta5"

Controller
`
$config = new Config(
            [
                'sampler' => [
                    'type' => 'const',
                    'param' => true,
                ],
                'logging' => true,
            ],
            'your-app-name'
        );
        $config->initializeTracer();

        $tracer = GlobalTracer::get();

        $scope = $tracer->startActiveSpan('TestSpan', []);
        $scope->close();

        $tracer->flush();
`
When I run controller's action I don't have any error. But Jaeger Dashbard empty

Dashbord 
http://localhost:16686/search
http://joxi.ru/nAypvqgcgjPWN2

**Comment by sergeyklay** [comment]
You shouldn't see any error. It's by design - OpenTracing shouldn't stop application in case of any unexpected situations. Could you sniff UDP packets using tcpdump, ngrep or something like that, is there any traffic? Finally, are there records in the traces storage (even if they were somehow not properly created)?

**Comment by Shketkol** [comment]
![image](https://user-images.githubusercontent.com/11447040/54745708-dd541000-4bd2-11e9-898f-1ba2a7ffc411.png)
