### ISSUE TITLE
ThriftUdpTransport is locked onto IPv4

### ISSUE THREAD

**Issue by FractalizeR** [jonahgeorge/jaeger-client-php#78]
```$this->socket = @socket_create(AF_INET, SOCK_DGRAM, SOL_UDP);``` line locks implementation to IPv4 without any options. It makes package unusable because my company is on IPv6 almost entierly. Supporting IPv4 without any options looks a bit dated to me.

Options I see:
* Autodetect scheme. If $host is IP address, you can tell if this is IPv4 or IPv6. If not - you can query DNS and then detect. 
* Allow options to be passed to a ThriftUdpTransport to specify IP protocol version.

**Comment by sergeyklay** [comment]
Could you help me by sending me a PR? I just don't have the bandwidth for this :)

**Comment by sergeyklay** [comment]
This is resolved in [`master`](https://github.com/jonahgeorge/jaeger-client-php/pull/113) branch. Thank you for the report, and for helping us make jaeger-client-php. And I am sorry about the delay.
