### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by carstensvendsen** [jonahgeorge/jaeger-client-php#92]
Hi, are you planning on making it compatible with php8? 

If this is not within your timeframe, would you be open for a pr?

**Comment by sergeyklay** [comment]
Hello! Yes, we will gladly accept a pull request :)

**Comment by enleur** [comment]
https://pecl.php.net/package/hrtime does not support php 8 yet. can we replace it?

**Comment by sergeyklay** [comment]
> https://pecl.php.net/package/hrtime does not support php 8 yet. can we replace it?
> 
> I see we got polyfill

Yeah, polyfill will be a viable solution. I'm sorry, I'm just a maintainer, not a developer. I don't have time to do this on my own right now. If you provide a PR, I would love to review it.

**Comment by egor-muindor** [comment]
Can you make a PHP 8 release from master?

**Comment by damnedest** [comment]
+1, can you make release?

**Comment by sergeyklay** [comment]
I apologize for completely overlooking this. Thank you for the reminder. I just released version 1.1.0: https://github.com/jonahgeorge/jaeger-client-php/releases/tag/v1.1.0
